### ISSUE TITLE
update README.md to provide install instructions 

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-vizard#12]
These can be derived from the [cookiecutter template](https://github.com/caporaso-lab/cookiecutter-qiime2-plugin). I think this would be useful to have to facilitate testing. You *should* be able to edit the templated environment file to install necessary dependencies, but let me know if that doesn't work.

**Comment by lizgehret** [comment]
Done! Take a look at the updates [here](https://github.com/qiime2/q2-vizard?tab=readme-ov-file#q2-vizard) and lmk if there's anything else you think I should add @gregcaporaso.

**Comment by gregcaporaso** [comment]
Looks good @lizgehret!
