### ISSUE TITLE
BUG: "TypeError: list indices must be integers or slices, not str"

### ISSUE THREAD

**Issue by ChristosMatzoros** [qiime2/q2-vizard#27]
Hey @lizgehret,

I ran into a small issue while working with the `scatterplot_2d` function in `scatterplot.py`. The function throws a `TypeError` when it tries to access an element in a list using a string key. Specifically, the `line group_dropdown_default = md_cols_categorical['legendDefault']` is the culprit. Since md_cols_categorical is a list, it doesn’t support string indexing, which led to the error.

```
File "/q2-vizard/q2_vizard/scatterplot.py", line 44, in scatterplot_2d
    group_dropdown_default = md_cols_categorical['legendDefault']
TypeError: list indices must be integers or slices, not str
```

I think the error was introduced with the last commit. Just changing that line to `group_dropdown_default = 'legendDefault'` should do the trick, since 'legendDefault' is already in the list.

Thank you

**Comment by lizgehret** [comment]
Hey @ChristosMatzoros,

Thanks for catching this! I was in the middle of making some changes to scatterplot on Thursday, and didn't finish up with testing before heading out for the long weekend. Glad to see that it's getting some good user testing 😅

I'll finish up testing this morning and then get your PR merged, thanks!
